services:
  rocm-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: rocm-pytorch-custom
    user: "${UID}:${GID}"
    container_name: rocm-pytorch
    ipc: host
    restart: unless-stopped
    ports:
      - "8888:8888"
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
      - render
      - kvm
    volumes:
      - /home/k-majick/Documents:/workspace
    working_dir: /workspace
    command: ["/workspace/rocm-pytorch/startup.sh"]


